SCRUM-34: Users tests
bebrachel/NSU_Sports_Complex pull request #14
Opened 2024-11-09 03:28 UTC by mkrikunov

2024-11-09 03:29 UTC, mkrikunov commented
Ща ребейзнусь

2024-11-09 03:40 UTC, olyaapg commented
> Ща ребейзнусь

а ревью

2024-11-09 03:41 UTC, mkrikunov commented
> > Ща ребейзнусь
> 
> а ревью

я же не мерджу в main

2024-11-09 06:21 UTC, olyaapg requested changes

2024-11-09 06:21 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
> +import lombok.AllArgsConstructor;
это же дублирует код конструктора

2024-11-09 06:21 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/UserRepositoryTest.java
мало методов тестируется

2024-11-15 06:00 UTC, mkrikunov commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/UserRepositoryTest.java
UserRepository наследует методы базового интерфейса JpaRepository, а также добавляет мой кастомный метод findByName. Я протестировал свой метод и один из методов базового интерфейса (просто на всякий пожарный, можно было и этого не делать, оставив тест только моего метода)

2024-11-15 06:07 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
> +import lombok.AllArgsConstructor;
она не дублирует, т.к. я, импортировав эту аннотацию, не использую ее (использовал раньше, удалил). Это просто импорт, который я забыл удалить. Если ты настолько хочешь докопаться, то сейчас удалю эту строчку и перезалью))

2024-11-15 14:08 UTC, olyaapg commented
Почему покрытие 0%, если это тесты

2024-11-30 03:54 UTC, olyaapg approved these changes

2024-11-30 03:54 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/service/UserServiceTest.java
> +        verify(userRepository, times(1)).save(user);
что такое verify

2024-11-30 03:54 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
> +    public User() {}
Можно использовать просто @NoArgsConstructor и @AllArgsConstructor

2024-11-30 03:54 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/UserRepositoryTest.java
> +                2, "Andrei Grigoriev-Apollonov", "andrei.grigoriev-apollonov@rambler.ru"));
а почему тут id меняется с 1 на 2? Или юзер изначально без id должен быть

2024-11-30 05:14 UTC, nocarend approved these changes

2024-11-30 05:14 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
ей Богу, где-то еще эту правку видел

2024-11-30 05:14 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
> +    public User(Integer id, String name, String email) {
У ломбока есть `@AllArgsConstructor` и `NoArgsConstructor` для таких случаев

2024-11-30 05:14 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
>  @Entity
еще советую посмотреть на `@Data` у ломбока

2024-11-30 05:14 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/SectionService.java
было лишним

2024-11-30 05:14 UTC, merged