SCRUM-36--Sections-Tests
bebrachel/NSU_Sports_Complex pull request #15
Opened 2024-11-09 03:39 UTC by olyaapg

2024-11-15 06:31 UTC, nocarend requested changes

2024-11-15 06:31 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
У тебя и у Миши есть эта правка
Почему так?

2024-11-15 06:31 UTC, nocarend commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/SectionRepositoryTest.java
> +        assertEquals("Бассейн НГУ", section.getPlace());
тогда уж все поля проверять?

2024-11-15 06:31 UTC, nocarend commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/SectionRepositoryTest.java
почему тесты на репозиторий, а не на сервис?

2024-11-15 14:13 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
так получилось

2024-11-15 14:14 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
(хз)

2024-11-15 14:15 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/SectionRepositoryTest.java
хотела сделать тесты на всё, начала с репо, чтобы понять, как оно делается

2024-11-15 14:15 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/repository/SectionRepositoryTest.java
> +        assertEquals("Бассейн НГУ", section.getPlace());
ок

2024-11-22 14:46 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
Решите, кто её должен оставить, а кто выпилить

2024-11-22 14:48 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    public boolean equals(Object obj) {
Умный Сонар говорит, что раз переопределяешь `equals`, то надо и `hashCode()`

2024-11-22 17:49 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    public boolean equals(Object obj) {
ok

2024-11-22 18:09 UTC, merged