SCRUM-28: users ans sections connection
bebrachel/NSU_Sports_Complex pull request #16
Opened 2024-11-09 05:23 UTC by mkrikunov

2024-11-09 05:25 UTC, mkrikunov commented
Связь работает, создается новая табличка. Почему-то, когда тестил в постмене, перестал создаваться юзер, причину не понял. @nocarend чекни, вдруг ты заметишь косяк

2024-11-09 05:37 UTC, mkrikunov commented
ааааай, application properties не тот закоммитил
ладно, потом исправлю

2024-11-15 06:24 UTC, nocarend requested changes

2024-11-15 06:24 UTC, nocarend commented on .github/workflows/ci.yml
этого не должно быть в твоих правках

2024-11-15 06:24 UTC, nocarend commented on backend/build.gradle
и этого

2024-11-15 06:24 UTC, nocarend commented on backend/checkstyle/checkstyle.xml
и этого

2024-11-15 06:24 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    public ResponseEntity<Section> updateSection(@PathVariable Integer id, @RequestBody Section section) {
Почему этот фрагмент есть и в твоем ревью? @olyaapg

2024-11-15 06:24 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    public ResponseEntity<Section> updateSection(@PathVariable Integer id, @RequestBody Section section) {
https://github.com/bebrachel/NSU_Sports_Complex/pull/15/files

2024-11-15 06:24 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
где сваггер

2024-11-15 06:24 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/UserController.java
> +@RequestMapping("/api/users")
и это почему-то у вас обоих @olyaapg 
https://github.com/bebrachel/NSU_Sports_Complex/pull/15/files

2024-11-15 06:24 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    private Integer capacity;
И какая же вместимость у секции?

2024-11-15 06:24 UTC, nocarend commented on backend/src/main/resources/application.properties
и вот этих правок не должно быть

2024-11-15 06:26 UTC, mkrikunov commented on backend/src/main/resources/application.properties
Про это писал выше, мой косяк, исправлю

2024-11-15 06:28 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    private Integer capacity;
Я так понимаю, что при создании секции мы инициализируем это поле. Какая вместимость нужна, такое число и вводится

2024-11-15 06:28 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/UserController.java
> +@RequestMapping("/api/users")
Вот это хз, не помню, кто именно это правил

2024-11-15 06:29 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    public ResponseEntity<Section> updateSection(@PathVariable Integer id, @RequestBody Section section) {
Я сделал ребейз, и произошла куча конфликтов с Олиными файлами. Решал конфликты, теперь эти файлы и у меня :/

2024-11-15 06:29 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/SectionController.java
> +    @PutMapping("/{id}")
Я сделал ребейз, и произошла куча конфликтов с Олиными файлами. Решал конфликты, теперь эти файлы и у меня :/

2024-11-15 06:30 UTC, mkrikunov commented on .github/workflows/ci.yml
Я эти файлы не трогал и хз, что в них и почему закоммитилось. Подскажи, почему они могли измениться и попасть в коммит?

2024-11-15 06:31 UTC, mkrikunov commented on backend/build.gradle
Я эти файлы не трогал и хз, что в них и почему закоммитилось. Подскажи, почему они могли измениться и попасть в коммит?

2024-11-15 06:31 UTC, mkrikunov commented on backend/checkstyle/checkstyle.xml
Я эти файлы не трогал и хз, что в них и почему закоммитилось. Подскажи, почему они могли измениться и попасть в коммит?

2024-11-15 14:53 UTC, olyaapg commented on .github/workflows/ci.yml
совет: просматривай перед коммитом файлы, которые добавляешь

2024-11-15 14:56 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/UserController.java
> +@RequestMapping("/api/users")
> и это почему-то у вас обоих @olyaapg https://github.com/bebrachel/NSU_Sports_Complex/pull/15/files

видимо из-за ребэйза

2024-11-15 14:56 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    private Integer capacity;
то есть у нас может быть только ограниченное число людей?

2024-11-15 16:03 UTC, nocarend commented on .github/workflows/ci.yml
Миша, это ты делал. Я не знаю, почему они могли попасть в коммит

2024-11-15 16:03 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    private Integer capacity;
Угу, непонятно почему число ограниченное

2024-11-22 02:27 UTC, nocarend commented
> Связь работает, создается новая табличка. Почему-то, когда тестил в постмене, перестал создаваться юзер, причину не понял. @nocarend чекни, вдруг ты заметишь косяк

Я, может, и замечу. Но, думаю, что ты справишься сам

2024-11-30 09:34 UTC, nocarend commented
Какой статус у этого пр?

2024-12-07 04:46 UTC, mkrikunov commented
> Какой статус у этого пр?

В процессе. Переписываю, меняю юзера на мембера

2024-12-07 04:50 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> +    private Integer capacity;
> Угу, непонятно почему число ограниченное

потому что будет ошибкой записать на борьбу 70 человек, если вместимость зала для борьбы 15-20 человек (или преподаватель может за занятие нормально работать только с двадцатью людьми, но не с сотней)

2024-12-20 08:51 UTC, olyaapg commented on .idea/.gitignore
ой-ой, а зачем папку .idea запушил?

2024-12-20 08:51 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/MemberConverter.java
> +                        Section section = new Section();
просто вызывай конвертер секций и все, не надо вручную это делать

2024-12-20 08:51 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/SectionConverter.java
> +                        Member member = new Member();
и тут почему не используешь конвертер?

2024-12-20 08:51 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/UserConverter.java
> +@Component
конвертер можно сделать как класс-утилита, как будто это всё-таки не полноценный компонент

2024-12-20 08:51 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/MemberServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Мембер не найден"));
Мембер не найден, мб лучше тогда участник?)) Просто забавно на русском звучит

2024-12-20 08:51 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/MemberServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Мембер не найден"));
это мамба фантастика

2024-12-20 11:12 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/MemberServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Мембер не найден"));
пусть будет мембер

2024-12-21 03:37 UTC, merged