SCRUM-38--Schedule-Entity
bebrachel/NSU_Sports_Complex pull request #17
Opened 2024-11-16 04:16 UTC by olyaapg

2024-11-30 03:41 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/SectionConverter.java
> +        section.setSchedule(ScheduleConverter.dtoToSchedule(sectionDTO.getSchedule()));
что с отступами?

2024-11-30 03:42 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/SectionConverter.java
> +        sectionDTO.setSchedule(ScheduleConverter.scheduleToDTO(section.getSchedule()));
что с отступами?

2024-11-30 03:43 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/TimeSlotConverter.java
> +            timeSlot.setDayOfWeek(DayOfWeek.valueOf(timeSlotDTO.getDayOfWeek()));
отступы?

2024-11-30 03:50 UTC, nocarend approved these changes

2024-11-30 03:54 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/SectionConverter.java
> +        sectionDTO.setSchedule(ScheduleConverter.scheduleToDTO(section.getSchedule()));
а что с ними

2024-11-30 09:33 UTC, nocarend requested changes

2024-11-30 09:33 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/TimeSlotConverter.java
> +            throw new IllegalArgumentException("Invalid time format. Expected HH:mm for startTime/endTime");
Тогда может экранировать неверную дату?

2024-12-05 08:19 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/converter/TimeSlotConverter.java
> +            throw new IllegalArgumentException("Invalid time format. Expected HH:mm for startTime/endTime");
в смысле помимо бросания исключения установить дефолтные значения?

2024-12-05 18:14 UTC, olyaapg commented
Нужно аппрув, тогда сделаю ребэйз на main, оттуда rebase на SCRUM-35 допилить информативное бросание ошибок

2024-12-06 01:56 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/dto/TimeSlotDTO.java
> +    @NotNull(message = "Day of the week must not be null")
о том, что `must not` следует из самой аннотации. Зачем это в сообщении писать?

2024-12-06 01:58 UTC, nocarend approved these changes
обожаю смотреть пулл реквесты на 500+ строк

2024-12-06 04:00 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/dto/TimeSlotDTO.java
> +    @NotNull(message = "Day of the week must not be null")
Я думала, что это тогда будет кастомное сообщение выводиться. Но я ошиблась
![image](https://github.com/user-attachments/assets/1f626292-b7b6-4bb3-966d-343e19d4b7a9)

2024-12-06 14:59 UTC, mkrikunov approved these changes

2024-12-06 15:38 UTC, merged