SCRUM-35--url-error-handling
bebrachel/NSU_Sports_Complex pull request #19
Opened 2024-11-23 02:57 UTC by olyaapg

…тивная ошибка

2024-11-30 04:29 UTC, nocarend approved these changes

2024-11-30 09:23 UTC, nocarend requested changes

2024-11-30 09:23 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/SectionServiceImpl.java
> +        System.out.println(section);
Это надо удалить

Или тут нормальное логгирование сделать

2024-11-30 09:23 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/SectionServiceImpl.java
> +        System.out.println(section);
И это

2024-11-30 09:24 UTC, nocarend commented
Отмена аппрува

2024-11-30 16:42 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/SectionServiceImpl.java
> +        System.out.println(section);
ептить, это что за гавно тут вылезло, этого не должно быть и не будет в скором времени

2024-11-30 16:42 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/service/impl/SectionServiceImpl.java
> +        System.out.println(section);
и это

2024-12-06 23:55 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/TimeSlot.java
> -
почему?

2024-12-06 23:55 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Section.java
> -    @Override
почему?

2024-12-06 23:55 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/Schedule.java
> -
почему?

2024-12-06 23:56 UTC, nocarend approved these changes

2024-12-07 03:26 UTC, merged