SCRUM-39: add news entity
bebrachel/NSU_Sports_Complex pull request #22
Opened 2024-12-07 03:43 UTC by mkrikunov

2024-12-07 03:54 UTC, mkrikunov commented
пока не ревьювьте, еще правок внесу

2024-12-07 04:29 UTC, mkrikunov commented
ну я чет хз, что тут еще протестить, вроде и так норм написал. Жду авторитетного мнения, коллеги)

2024-12-07 04:35 UTC, mkrikunov commented
ща, стоп ревью, еще тестов накидаю

2024-12-07 04:45 UTC, mkrikunov commented
Коллеги, жду ваши ревью
![image](https://github.com/user-attachments/assets/ccd0f413-8d02-4916-9d1c-68a28da4ba78)

2024-12-07 05:40 UTC, nocarend commented
![image](https://github.com/user-attachments/assets/77454253-0812-4608-ad5d-f96edcd9d68c)

я не понимаю почему тут много коммитов, не относящихся к делу

2024-12-07 06:22 UTC, olyaapg requested changes

2024-12-07 06:22 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(NewsController.class);
с каких пор ты используешь LOGGER

2024-12-07 06:22 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +    })
А где @ApiResponse(responseCode = "200", description = "Список новостей.", content = {
                    @Content(mediaType = "application/json", schema =
                    @Schema(implementation = List.class))
            })

2024-12-07 06:22 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +                .collect(Collectors.toList());
Replace this usage of 'Stream. collect(Collectors. toList())' with 'Stream. toList()' and ensure that the list is unmodified.

2024-12-07 06:22 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +            LOGGER.error("Error fetching news with id {}: {}", id, e.getMessage());
Это же не Log4J? Прст там по документации пишут, что логгер умный и не нужно передавать e.getMessage(), достаточно саму ошибку передать, а он всё как надо сделает. Ну а тут хз

2024-12-07 06:22 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/dto/NewsDTO.java
> +    @NotBlank(message = "Title cannot be blank")
зачем message

2024-12-07 06:22 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +                new News(1, "Title 1", "Content 1", LocalDateTime.now(), LocalDateTime.now(), "Author 1"),
каждый раз при запуске будет новое время создаваться. А тесты должны быть детерминированными. Хотя тут это не так важно

2024-12-07 06:22 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +        NewsDTO newsDTO = new NewsDTO(null, "Title", "Content", LocalDateTime.now(), LocalDateTime.now(), "Author");
а зачем ты их вручную прописываешь, когда у тебя есть конвертер

2024-12-07 06:22 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +        assertEquals(1, response.getBody().getId());
и ты не проверяешь, что сохранилась именно та новость, что и была создана. По идее у них время должно отличаться

2024-12-07 06:22 UTC, olyaapg commented on backend/src/test/java/ru/nsu/sports/complex/backend/service/NewsServiceTest.java
> +                new News(1, "Title 1", "Content 1", null, null, "Joe Biden"),
время же не может быть null у тебя в entity

2024-12-07 06:57 UTC, olyaapg requested changes

2024-12-07 06:57 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/News.java
> +public class News {
А где привязка к секции?

2024-12-07 06:57 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/News.java
> +    private String author;
каким образом будет определяться автор?

2024-12-07 08:08 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(NewsController.class);
угу, был же какой-то встроенный

2024-12-07 08:10 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/dto/NewsDTO.java
> +    @NotBlank(message = "Title cannot be blank")
скопипастил откуда-то мб

2024-12-07 08:10 UTC, nocarend commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
> +import lombok.*;
ппц правки

2024-12-07 08:14 UTC, nocarend commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +                new News(1, "Title 1", "Content 1", LocalDateTime.now(), LocalDateTime.now(), "Author 1"),
не важно. Даже веселее будет, мб какой-то баг находиться будет

2024-12-07 08:15 UTC, nocarend commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +    void setUp() {
наверное, сюда можно запихать создание данных, которые используются в тестах

2024-12-07 08:16 UTC, nocarend commented on backend/src/test/java/ru/nsu/sports/complex/backend/converter/NewsConverterTest.java
> +    void setUp() {
тесты конвертера это ок, но вообще не обязательно

2024-12-07 08:19 UTC, nocarend commented
это очень плохо, что у нас в каждом пр конфликтв

2024-12-12 13:50 UTC, mkrikunov commented
> я не понимаю почему тут много коммитов, не относящихся к делу

я сделал гит пулл, подтянулась куча фигни + подтянулась куча конфликтов (конфликты в секциях и расписании, которые возникали и в других ветках)

2024-12-12 13:55 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(NewsController.class);
LOGGER использую с октября, пользовался им еще  UserController. Могу использовать log4j, мне без разницы)

2024-12-12 13:57 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +    })
потерялося, исправлюся)

2024-12-12 13:58 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/controller/NewsController.java
> +            LOGGER.error("Error fetching news with id {}: {}", id, e.getMessage());
Про логгер писал выше. Если нужен другой логгер, поменяю, а так работает вроде норм. Про передачу ошибок почитаю в документации, спасибо)

2024-12-12 13:59 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/dto/NewsDTO.java
> +    @NotBlank(message = "Title cannot be blank")
> скопипастил откуда-то мб

yes. Какой-то форум сказал, что так правильно, я поверил. Раз есть вопросы, то перепроверю

2024-12-12 13:59 UTC, mkrikunov commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +                new News(1, "Title 1", "Content 1", LocalDateTime.now(), LocalDateTime.now(), "Author 1"),
кстати, да, косячок, он может сказаться в других местах кода, надо поправить

2024-12-12 14:02 UTC, mkrikunov commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +        NewsDTO newsDTO = new NewsDTO(null, "Title", "Content", LocalDateTime.now(), LocalDateTime.now(), "Author");
да чтоб скучно не было)

2024-12-12 14:02 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/News.java
> +public class News {
Считаю, что привязка не нужна. Подробнее об этом написал в беседе

2024-12-12 14:04 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/News.java
> +    private String author;
задаваться ручками при создании новости. Вообще, не очень вижу смысл в авторе, потому что новости будут публиковаться от имени руководства спорткомплекса. Но подумал, что можно указывать конкретного человека, кто эту новость прописывал, поэтому добавил это поле

2024-12-12 14:05 UTC, mkrikunov commented on backend/src/main/java/ru/nsu/sports/complex/backend/model/User.java
> +import lombok.*;
правка для рестарта сонара, иначе он не перезапускался. Писал об этом в коммите

2024-12-12 14:05 UTC, mkrikunov commented on backend/src/test/java/ru/nsu/sports/complex/backend/controller/NewsControllerTest.java
> +    void setUp() {
Хорошая идея, спасибо)

2024-12-12 14:06 UTC, mkrikunov commented
> это очень плохо, что у нас в каждом пр конфликтв

они тянутся с мейна. Вроде Оля уже починила это, и при дальнейшей работе с мейном в ветках конфликтов быть не должно (было бы славно)

2024-12-12 14:25 UTC, olyaapg commented on backend/src/main/java/ru/nsu/sports/complex/backend/dto/NewsDTO.java
> +    @NotBlank(message = "Title cannot be blank")
> > скопипастил откуда-то мб
> 
> yes. Какой-то форум сказал, что так правильно, я поверил. Раз есть вопросы, то перепроверю

прост мне Коля тоже писал про этот message, мне его чатик подсказывал. Я думала, это сообщение будет красиво выводиться, а оно не выводится никуда

2024-12-13 17:12 UTC, mkrikunov commented
Я так понял, покрытие ноль, потому что не покрывается код из последнего коммита. А так, почти ничего нового по сравнению с предыдущей проверкой покрытия, где все было гуд. Кстати, локально все тесты проходят, а тут тоже какой-то фейл, мб я чего-то не понимаю

2024-12-14 02:36 UTC, olyaapg approved these changes

2024-12-20 13:22 UTC, olyaapg requested changes

2024-12-20 13:22 UTC, olyaapg commented on backend/src/main/resources/db/migration/V1__Initial_schema.sql
> +CREATE TABLE public.news
каждая правка - новая миграция. Зачем ты создаешь таблицу в изначальной?? Отдельный sql файл должен быть.

2024-12-20 13:24 UTC, mkrikunov commented on backend/src/main/resources/db/migration/V1__Initial_schema.sql
> +CREATE TABLE public.news
да епрст

2024-12-20 13:54 UTC, olyaapg requested changes

2024-12-20 13:54 UTC, olyaapg commented on backend/src/main/resources/db/migration/V2__news_migration.sql
> +    id    integer NOT NULL,
-- Name: sections_id_seq; Type: SEQUENCE; Schema: public;
ALTER TABLE public.sections
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.sections_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

нужно добавить автогенерацию айди

2024-12-20 13:57 UTC, mkrikunov commented on backend/src/main/resources/db/migration/V2__news_migration.sql
> +    id    integer NOT NULL,
![image](https://github.com/user-attachments/assets/b83d7cd5-27cf-423d-a175-fce973176794)

2024-12-20 14:27 UTC, olyaapg approved these changes

2024-12-20 14:51 UTC, merged